import { ThemeConfig, ThemeId } from '@/types';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  classic: {
    id: 'classic',
    name: 'Classic Documentation',
    description: 'Clean, balanced documentation style ideal for general tech projects.',
    category: 'Documentation',
    previewColor: '#2563eb',
    styles: {
      fontFamily: 'Inter, sans-serif',
      headingFontFamily: 'Inter, sans-serif',
      codeFontFamily: 'JetBrains Mono, monospace',
      fontSize: '15px',
      lineHeight: '1.65',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      headingColor: '#0f172a',
      accentColor: '#2563eb',
      codeBg: '#f1f5f9',
      codeTextColor: '#0f172a',
      borderColor: '#e2e8f0',
      tableHeaderBg: '#f8fafc',
      tableAltRowBg: '#f1f5f9',
      blockquoteBg: '#eff6ff',
      blockquoteBorderColor: '#3b82f6',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      padding: '40px',
    },
  },
  github: {
    id: 'github',
    name: 'GitHub Style',
    description: 'Authentic GitHub README look and feel with crisp borders and code blocks.',
    category: 'Developer',
    previewColor: '#24292e',
    styles: {
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      headingFontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      codeFontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
      fontSize: '16px',
      lineHeight: '1.5',
      backgroundColor: '#ffffff',
      textColor: '#24292e',
      headingColor: '#1f2328',
      accentColor: '#0969da',
      codeBg: '#f6f8fa',
      codeTextColor: '#1f2328',
      borderColor: '#d0d7de',
      tableHeaderBg: '#f6f8fa',
      tableAltRowBg: '#f6f8fa',
      blockquoteBg: '#ffffff',
      blockquoteBorderColor: '#d0d7de',
      shadow: '0 1px 3px rgba(27,31,35,0.12)',
      padding: '45px',
    },
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate Report',
    description: 'Executive navy headers, crisp grid alignments, and formal typography.',
    category: 'Enterprise',
    previewColor: '#0f172a',
    styles: {
      fontFamily: 'Inter, sans-serif',
      headingFontFamily: 'Inter, sans-serif',
      codeFontFamily: 'JetBrains Mono, monospace',
      fontSize: '15px',
      lineHeight: '1.6',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      headingColor: '#0f172a',
      accentColor: '#0284c7',
      codeBg: '#f8fafc',
      codeTextColor: '#0f172a',
      borderColor: '#cbd5e1',
      tableHeaderBg: '#0f172a',
      tableAltRowBg: '#f8fafc',
      blockquoteBg: '#f0f9ff',
      blockquoteBorderColor: '#0284c7',
      shadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      padding: '50px',
    },
  },
  academic: {
    id: 'academic',
    name: 'Academic Paper',
    description: 'Traditional Serif layout, elegant sub-headers, and formal paper style.',
    category: 'Publication',
    previewColor: '#334155',
    styles: {
      fontFamily: 'Georgia, serif',
      headingFontFamily: 'Times New Roman, Times, serif',
      codeFontFamily: 'Courier New, monospace',
      fontSize: '15px',
      lineHeight: '1.7',
      backgroundColor: '#fcfcfc',
      textColor: '#1c1917',
      headingColor: '#0c0a09',
      accentColor: '#854d0e',
      codeBg: '#f5f5f4',
      codeTextColor: '#1c1917',
      borderColor: '#d6d3d1',
      tableHeaderBg: '#e7e5e4',
      tableAltRowBg: '#f5f5f4',
      blockquoteBg: '#fafaf9',
      blockquoteBorderColor: '#a8a29e',
      shadow: 'none',
      padding: '55px',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark Mode PDF',
    description: 'Sleek dark theme optimized for modern dark document viewports.',
    category: 'Developer',
    previewColor: '#0f172a',
    styles: {
      fontFamily: 'Inter, sans-serif',
      headingFontFamily: 'Inter, sans-serif',
      codeFontFamily: 'JetBrains Mono, monospace',
      fontSize: '15px',
      lineHeight: '1.65',
      backgroundColor: '#0f172a',
      textColor: '#e2e8f0',
      headingColor: '#f8fafc',
      accentColor: '#38bdf8',
      codeBg: '#1e293b',
      codeTextColor: '#f8fafc',
      borderColor: '#334155',
      tableHeaderBg: '#1e293b',
      tableAltRowBg: '#1e293b',
      blockquoteBg: '#1e293b',
      blockquoteBorderColor: '#38bdf8',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.5)',
      padding: '40px',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimalist',
    description: 'Ultra-clean layout focusing purely on readability and whitespace.',
    category: 'Modern',
    previewColor: '#64748b',
    styles: {
      fontFamily: 'Inter, sans-serif',
      headingFontFamily: 'Inter, sans-serif',
      codeFontFamily: 'JetBrains Mono, monospace',
      fontSize: '15px',
      lineHeight: '1.7',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      headingColor: '#0f172a',
      accentColor: '#475569',
      codeBg: '#f8fafc',
      codeTextColor: '#0f172a',
      borderColor: '#f1f5f9',
      tableHeaderBg: '#ffffff',
      tableAltRowBg: '#f8fafc',
      blockquoteBg: '#f8fafc',
      blockquoteBorderColor: '#cbd5e1',
      shadow: 'none',
      padding: '40px',
    },
  },
  modern: {
    id: 'modern',
    name: 'Modern Tech',
    description: 'Vibrant indigo accents, soft gradients, and high contrast headings.',
    category: 'Modern',
    previewColor: '#6366f1',
    styles: {
      fontFamily: 'Inter, sans-serif',
      headingFontFamily: 'Inter, sans-serif',
      codeFontFamily: 'JetBrains Mono, monospace',
      fontSize: '15px',
      lineHeight: '1.65',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      headingColor: '#312e81',
      accentColor: '#6366f1',
      codeBg: '#eef2ff',
      codeTextColor: '#312e81',
      borderColor: '#e0e7ff',
      tableHeaderBg: '#e0e7ff',
      tableAltRowBg: '#f5f3ff',
      blockquoteBg: '#eef2ff',
      blockquoteBorderColor: '#6366f1',
      shadow: '0 4px 14px 0 rgba(99, 102, 241, 0.15)',
      padding: '45px',
    },
  },
  book: {
    id: 'book',
    name: 'Book Style',
    description: 'Warm cream page tone with elegant book layout proportions.',
    category: 'Publication',
    previewColor: '#78350f',
    styles: {
      fontFamily: 'Georgia, serif',
      headingFontFamily: 'Georgia, serif',
      codeFontFamily: 'Courier New, monospace',
      fontSize: '16px',
      lineHeight: '1.75',
      backgroundColor: '#fefcbf',
      textColor: '#27272a',
      headingColor: '#78350f',
      accentColor: '#b45309',
      codeBg: '#fef3c7',
      codeTextColor: '#78350f',
      borderColor: '#fde68a',
      tableHeaderBg: '#fef3c7',
      tableAltRowBg: '#fffbeb',
      blockquoteBg: '#fef3c7',
      blockquoteBorderColor: '#d97706',
      shadow: '0 4px 6px -1px rgba(120, 53, 15, 0.1)',
      padding: '50px',
    },
  },
  resume: {
    id: 'resume',
    name: 'Executive Resume',
    description: 'Compact layout optimized for technical specs, CVs, and handoffs.',
    category: 'Professional',
    previewColor: '#0d9488',
    styles: {
      fontFamily: 'Roboto, sans-serif',
      headingFontFamily: 'Roboto, sans-serif',
      codeFontFamily: 'JetBrains Mono, monospace',
      fontSize: '14px',
      lineHeight: '1.55',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      headingColor: '#111827',
      accentColor: '#0d9488',
      codeBg: '#f0fdf4',
      codeTextColor: '#065f46',
      borderColor: '#e5e7eb',
      tableHeaderBg: '#f0fdf4',
      tableAltRowBg: '#f9fafb',
      blockquoteBg: '#f0fdf4',
      blockquoteBorderColor: '#0d9488',
      shadow: 'none',
      padding: '35px',
    },
  },
  'google-docs': {
    id: 'google-docs',
    name: 'Google Docs Style',
    description: 'Familiar document editor styling with blue headings and clean margins.',
    category: 'Standard',
    previewColor: '#1a73e8',
    styles: {
      fontFamily: 'Arial, sans-serif',
      headingFontFamily: 'Arial, sans-serif',
      codeFontFamily: 'Consolas, monospace',
      fontSize: '15px',
      lineHeight: '1.6',
      backgroundColor: '#ffffff',
      textColor: '#202124',
      headingColor: '#1a73e8',
      accentColor: '#1a73e8',
      codeBg: '#f1f3f4',
      codeTextColor: '#202124',
      borderColor: '#dadce0',
      tableHeaderBg: '#f1f3f4',
      tableAltRowBg: '#f8f9fa',
      blockquoteBg: '#e8f0fe',
      blockquoteBorderColor: '#1a73e8',
      shadow: '0 1px 2px 0 rgba(60,64,67,0.3)',
      padding: '48px',
    },
  },
  word: {
    id: 'word',
    name: 'Microsoft Word Style',
    description: 'Classic Office Word styling with Calibri typography and navy blue headings.',
    category: 'Standard',
    previewColor: '#2b579a',
    styles: {
      fontFamily: 'Calibri, sans-serif',
      headingFontFamily: 'Calibri, sans-serif',
      codeFontFamily: 'Consolas, monospace',
      fontSize: '15px',
      lineHeight: '1.5',
      backgroundColor: '#ffffff',
      textColor: '#262626',
      headingColor: '#2b579a',
      accentColor: '#2b579a',
      codeBg: '#f2f2f2',
      codeTextColor: '#262626',
      borderColor: '#d9d9d9',
      tableHeaderBg: '#2b579a',
      tableAltRowBg: '#f2f2f2',
      blockquoteBg: '#f2f5f9',
      blockquoteBorderColor: '#2b579a',
      shadow: '0 1px 3px rgba(0,0,0,0.1)',
      padding: '50px',
    },
  },
};
